# Generated by Django 2.1.7 on 2019-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realuser',
            name='email_id',
            field=models.CharField(max_length=36),
        ),
    ]
